### ISSUE TITLE
Where does `CONTRIBUTING.md` disappeared?

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#138]
I’ve wanted to update `CONTRIBUTING.md`, but it somewhat disappeared. It might have been overwritten by some commit.

Should I re-create it?

**Comment by emagnier** [comment]
It's on master.

**Comment by tukusejssirs** [comment]
Okay. But still don’t get it that some commits land into `master`, others into `romcal-es6`. :smiley:

**Comment by emagnier** [comment]
Because romcal-es6 was originally a feature/scoped branch (revamp code to es6), but became little by little a jungle branch. We continued to work on it because too much was already underway. But master remain the right branch for minor issues and bug fixes, and romcal-es6 will disappear as soon as we can.
