### ISSUE TITLE
Calendar rankings (inheritance)

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#48]
In order to fix issue #13, we should create something like calendar ‘ranks’, i.e. calendars for more area types.

Currently, we only support General Roman Calendar and so-called ‘national’ calendars. The problem is that officially, there’s no such thing as national calendar (in the sense we use it); there are ~~calendars of dioceses~~ particular calendars. Nevertheless, I would leave the national calendars and besides dioceasan ones I would add continental a parish calendars, too. Here’s a summary:

- general
- continental (Africa, Asia, Australia and Oceania, Europe, North America, South America)
   - this would contain all continent specific celebrations (like patron saints of the particular continent) upon generation,
   - it would be built with General Roman Calendar as bass
- national
    - this would be a calendar for the particular country (like the UK, the US, Malaysia, Slovakia, etc)
    - it would be built upon continental calendar (and through it upon the General Roman)
- diocesan
    - liturgical calendar of diocese
    - built upon national (and throuth it upon continental and general)
- parish
    - this one usually does not exist, but still I think it (once) would be a nice feature;
    - it would contain celebrations that would be celebrated only in that particular parish, like the church patronage
    - later on, when/if we bring the ‘directory-style output’, we might include some other special days … for exampoe, in our parish, on the 18th of each month we pray for our parish
    - built upon diocesan calendar.

Note: There might be all/some dioceses in one country grouped together (like in Slovakia or the UK), or even countries (like Austria, Germany and Switzerland). In my opinion, it would be nice to have an option to generate these grouped calendars (either national, diocesan or parish) as grouped calendars, but also separately (although they would be same) in case the generator (person) won‘t know they are grouped.

**Comment by emagnier** [comment]
And this might be related to #73. If we go ahead on this, the `national` directory will have no senses.

I've similar needs on my side, and I'll try to expose soon how it could be implemented.

**Comment by emagnier** [comment]
What the purpose of grouping calendar together? I think in France we don't have this need, so I'm not sure what this addition could bring.
Can we consider it as a combination, like combine the french calendar and the slovak calendar to get a new combined calendar?
But we will get an issue with celebrations on both calendars that might have different properties (date, rank type, meta...).

**Comment by tukusejssirs** [comment]
> What the purpose of grouping calendar together? I think in France we don't have this need, so I'm not sure what this addition could bring.

Well, I think that even in France you dioceses and parishes. Each diocese might (and usually does) have some special (ie. different from general/national calendar) celebrations, like the diocese patron celebrated as solemnity (see issue #13). That is, the `france.js` would contain only celebrations celebrated in every part of France the same way, the ‘diocesian’ calendar would contain overrides. Same would apply to continents—they would contain `general.js` overrides (like Patron of Europe saints), countries would override continents, etc.

> Can we consider it as a combination, like combine the french calendar and the slovak calendar to get a new combined calendar?
> But we will get an issue with celebrations on both calendars that might have different properties (date, rank type, meta...).

I don’t think so.

**Comment by emagnier** [comment]
Ok so I don't see what the advantage of grouping together different calendars.

The easiest way in terms of information architecture and software development is to go with **inheritance**.

- Defined parish calendars will inherit from a diocesan calendar.
- Diocesan calendars will inherit from a national calendar.
- National calendars will inherit from a continental calendar.
- Continental calendars will inherit from the general calendar.

Everything defined at a higher level will descend to a lower level, but not the opposite.
Something defined in a national calendar will be present in diocesan and parish calendars (until they are redefined or dropped), but not in continental and general calendars (like actually between general and national calendars).

Each calendar will have an `inheritFrom` property and a `name` property. For example, the Slovak calendar will have `inheritFrom: europe`, and the European calendar will have `inheritFrom: general`.

This architecture will also make romcal easiest to extend with third party calendars. For example, I could load romcal on a third party app, and inject a calendar between the general calendar and the continental calendars (or between any other calendar levels) and extend existing calendars (to redefine their inheritance). This might be particularly useful for religious communities that also have their proper calendar, and are present in different countries (this is a need I currently have).

Parish calendars should not be integrated in the main romcal repo, because they are very specific. But they could be defined easily in a third party repo having romcal as a dependency. From a third party app/repo you will be able to extend romcal to add any custom calendars you want, or edit an existing one.

The concept of inheritance is the simple way to address all theses needs, and is very flexible. Technically, you might have as much as calendar levels you want. But to avoid a mess in the calendar directory, we have to define a naming convention for all theses calendar files. I suggest to use the continental 2-letter code, the kebab-case between each entity, and PascalCase for each name. For example, `EU-France-Strasbourg.js`, or `NA-Canada-Montreal.js`.

**Comment by tukusejssirs** [comment]
> There might be _countries_ grouped together (like Austria, Germany and Switzerland).

I’ve found this in my initial comment (the description). Now I see what are you talking about when you talk about _groups_.

Basically, I have found that the bishop conferences of Austrica, Germany and Switzerland agreen upon a single (grouped/joint) calendar used in all of these countries. I have no idea if/how this should be implemented, but I think it might good idea reflect this in `romcal`.

> This architecture will also make romcal easiest to extend with third party calendars. For example, I could load romcal on a third party app, and inject a calendar between the general calendar and the continental calendars (or between any other calendar levels) and extend existing calendars (to redefine their inheritance). This might be particularly useful for religious communities that also have their proper calendar, and are present in different countries (this is a need I currently have).

Well, yeah I’ve also thought about the religious calendar (which might be supercalendars or subcalendars based on the particular view point). I thought I have noted this here (or in another issue). I’d like to include even these calendars.

> Parish calendars should not be integrated in the main romcal repo, because they are very specific. But they could be defined easily in a third party repo having romcal as a dependency. From a third party app/repo you will be able to extend romcal to add any custom calendars you want, or edit an existing one.

Well, I wanted to integrate the parish calendars, but I think it would increase the repo/package size substantially. But if go the route of separate repo, could (I mean you :smiley:) create one? I’d like to add some parishes. Also I would how to to build `romcal` including that repo. But then we might also let the users/devs to build any _custom_ build based on how many calendar levels should be integrated.

> I suggest to use the continental 2-letter code, the kebab-case between each entity, and PascalCase for each name. For example, `EU-France-Strasbourg.js`, or `NA-Canada-Montreal.js`.

With everything else I agree. Here I’d note that if we include country groups, how will we differentiate betwen `austria` and `austria-germany-switzerland`, as I think that there should be som ‘symlinks’ of single countries to the grouped calendar.

---

On the relation with #73: Indeed it is related, but #73 says there we should correct name.

**Comment by emagnier** [comment]
I'm not in favour to create kind of `austria-germany-switzerland` calendar files, but to create a calendar combinaison feature, to group them together on demand. Meaning instead of select one calendar, we could select multiple calendars, and romcal will be able to combine and output them together, for example: `calendar: [austria, germany, switzerland]`
But group/combine calendars together is a feature out of scope here. This needs should be addressed later. Calendar ranks are already something big.

**Comment by tukusejssirs** [comment]
Well, I think we mix _calendar groups_ (i.e. what you are talking about, e.g. `calendar: [austria, germany, switzerland]`), which might not be even used in the liturgy anyway; and a _single calendar used across multiple countries (and possible dioceses). I am talking about the latter; as the [Wiki](https://en.wikipedia.org/wiki/General_Roman_Calendar#Austria,_Germany,_Switzerland) states it:

> The Episcopal Conferences of Austria, Germany, and Switzerland share one regional proper calendar, although each country remains free to insert additional celebrations (Austria, for example, has inscribed the optional memorial of Blessed Charles of Austria for its territory on 21 October).

**Comment by emagnier** [comment]
Understood. So if Austria, Germany, and Switzerland share one regional proper calendar, this could looks:
```
calendars
|--NA
|--NA-Canada
|--NA-Canada-Montreal
|--EU
|--EU-AustriaGermanySwitzerland
|--EU-Austria
|--EU-France
|--EU-France-Bordeaux
|--EU-France-LaRochelle
|--EU-France-Marseille
|--EU-France-Paris
|--EU-France-Strasbourg
|--EU-France-Toulouse
|--EU-Germany
|--EU-Slovakia
|--EU-Switzerland
|--OC
|--OC-Australia
```
Austria, Germany, and Switzerland remain a particular case, but I suggest to keep anyway a simple file structure. Internally, `EU-Austria`, `EU-Germany`, and `EU-Switzerland` will inherit from `EU-AustriaGermanySwitzerland`, and this last one will inherit from `EU`.

**Comment by tukusejssirs** [comment]
Okay, that sound great to me. Just to make sure I got it right: when a user chooses to output Austrian calendar, `romcal` will process it the following way:

```bash
general → EU → EU-AustriaGermanySwitzerland → EU-Austria
```

where the `general` calendar is used and all the other calendars are used as overrides in the left-to-right order.

Later on, we could even continue the process like this:

```bash
general → EU → EU-AustriaGermanySwitzerland → EU-Austria → EU-Austria-DioceseName →
  → EU-Austria-DioceseName-ParishName
```

Is that right?

**Comment by emagnier** [comment]
That's right!

**Comment by tukusejssirs** [comment]
Then this is what I wanted when I have opened this issue.

Still one thing: the religious (sub/super)calendars should be implemented in this repo. They should be only at the end (rightmost place) of the process described above (e.g. `general` → `EU` → `dominican`), never in the middle (e.g. `general` → `dominican` → `EU`). Therefore, they should be treated a bit special. You might already thought about this. :smiley:

**Comment by tukusejssirs** [comment]
Just a note: there might a (sort of) group calendar for China, Hong Kong and Taiwan ([src](https://en.wikipedia.org/wiki/General_Roman_Calendar#China,_Hong_Kong_and_Taiwan)).

**Comment by jarosz** [comment]
There's a document "Universal Norms on the Liturgical Year and the New General Roman Calendar", which covers this topic from the Church point of view (not developer-oriented :)). This is what I came up with, to be more consistent with the Church organization.

Point 48: "a calendar, which is either **general** or **particular**, depending on whether it has been laid down for the use of the entire Roman Rite, or for the use of a Particular Church or religious family"

Point 51: "there is nevertheless nothing to prevent entire provinces, regions, nations, or even larger areas, having Calendars and Propers in **common**"

- "general" calendar (the Holy See)
- "common" calendars (bishops' conference) - bishops may be organized in a conference of one country (general rule) or multiple countries, or only few dioceses of one country. That's why I would question "continental" and "national", because not all continents have shared calendar. There may be several such calendars for a region (like in the case of austria and austria-germany-switzerland)
- "particular" (diocese / religious family) - it should be possible to combine both, with the priority for a diocesan one
- "individual" (parish or different kind of community)

**Comment by emagnier** [comment]
Thank you for these great precisions. It doesn't change the software architecture, but might redefine a bit how to structure all these calendars together.

**Comment by tukusejssirs** [comment]
> That's why I would question "continental" and "national", because not all continents have shared calendar.

I’ve never there are such calendars. The reasonI suggested to implement them is that the _common_ patrons (like patron of Europe) could be defined there. There would eliminate the need to (re)define these celebration in each country of a continent.

> "particular" (diocese / religious family) - it should be possible to combine both, with the priority for a diocesan one. It's hard for me to imagine combining more than two of this kind.

As @emagnier has already proposed, 6echnically thi possible. I don’t the non-official ‘calendars (like continental ones) wuld be uses by the users, but they could aid to minimise the code (my previous paragraph).

> "individual" (parish or different kind of community) - this is unofficial, so maybe there should be none such calendars in the repo, only example how to create your own. However, rvery parish should celebrate the church patron (some have more than one). I think there should be possibility to combine multiple individual calendars as well.

Again, I know these are not official calendars. And they would inlude church patrons, parish patrons, dedication of the church mostly. This could aid the parish websites in the future.

**Comment by tukusejssirs** [comment]
I talked with @emagnier [here](https://github.com/romcal/romcal/pull/169#issuecomment-593099347) about another great addition, but it is twofold:
1. provide the calendar name in which the particular celebration is defined (`general` or one of the particular calendars);
2. if the celebration name is defined in a particular calendar, it might be good idea if we provide what has changed in comparison with the `general` calendar (there might be multiple changes):
   - `addition`:
      - the celebration does not exist in `general`;
      - it is defined in the particular calendar only;
   - `date`:
      - the celebration is defined also in `general`, but the celebration date is changed in the particular calendar;
   - `name`:
      - the celebration is defined also in `general`, but the celebration name is changed in the particular calendar;
   - `title`:
      - the celebration is defined also in `general`, but the celebration title(s) (e.g. the _patron titles_) is changed in the particular calendar;
   - `color`:
      - the celebration is defined also in `general`, but the liturgical colour of the celebration is changed in the particular calendar;
      - I am not sure if this might happen, but I think it is possible.

**Comment by tukusejssirs** [comment]
@emagnier, we should not forget about _provinces_ (or [_metropolias_/_metropolises_](https://en.wikipedia.org/wiki/Metropolis_(religious_jurisdiction)) if you wish).

**Comment by emagnier** [comment]
This feature is now implemented in romcal `v3`.
