### ISSUE TITLE
Firefox: `index.html`: This page uses the non standard property “zoom”

### ISSUE THREAD

**Issue by tukusejssirs** [romcal/romcal#84]
After opening index.html and then the browser console, Firefox showed me the following warning (it might be a good idea to fix it):

```bash
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.
```

I use Firefox Nightly (current version 72.0a1) on CentOS 7 x86_64.

**Comment by jarosz** [comment]
Same in 71.0 on Windows, fixed with bootstrap update.

**Comment by emagnier** [comment]
Good to know 👍 

I'm also wondering, do we really need bootstrap?

**Comment by jarosz** [comment]
It depends what do we want index.html to be. I can imagine it as a romcal.io front page (#80) with a calendar. It can be achieved with or without bootstrap, but I think it could be a solid foundation.

**Comment by tukusejssirs** [comment]
Well, I think that the example (`index.html`) should be removed from the repo altogether. The website (like `romcal.io`) would look better as an example _and_ as a website users could get the info `romcal` can provide. So I vote for this, although I know that the website could another ‘burden’ to maintain. :smiley:

**Comment by emagnier** [comment]
It still good to have this file in the main romcal repo, as an example, but moved in the `dist` directory.
But it should be as simple as possible, so I will recommend removing Bootstrap here (as well as most of the other plugin added to the page).

From webpack it's possible to generate 2 versions of the bundled file. One for modern browsers (95%), and another one for old browsers that don't support new es6 features and syntax. We should go in that direction instead (if we want to support the 5% old browsers). We also have to work on a way to lazy load locales and calendars in the browser, because actually this library for browsers is still a bit heavy (636 KB minified).

Also this file might be renamed to something like `romcal-demo.html` or `sample.html` and generated by one of the build scripts (from a template), so not included in the codebase.

The possible future romcal website should use instead a romcal REST API, using a more modern approach to consume data from romcal, and have a better separation between frontend and backend.

**Comment by tukusejssirs** [comment]
@emagnier, you have my vote. :smiley:
